VERSION_MAYOR = 0
VERSION_MINOR = 2
VERSION_PATCH = 0

VERSION_STRING = F'{VERSION_MAYOR}.{VERSION_MINOR}.{VERSION_PATCH}'

KANJI_FORMS_URL = 'https://docs.google.com/spreadsheets/d/1aw0ihw0RpmejWLTUynrFYjmOfLdzcPVrDX7UM50lwBY/edit#gid=2109245908'
